# Configuration:
# 
# disabled
#   false if tracking tag should be shown
# use_async
#   Set to true if you want to use asynchronous tracking
# url
#   The url of your piwik instance (e.g. localhost/piwik/
# id_site
#   The id of your website inside Piwik
#
production:
  piwik: &piwik_defaults
    id_site: <%= ENV["PIWIK_ID_SIZE"] %>
    url: <%= ENV["PIWIK_URL"] %>
    disabled: <%= ENV["PIWIK_URL"] ? "false" : "true" %>
    use_async: false

development:
  piwik: *piwik_defaults

test:
  piwik:
    disabled: true
